services:
  - type: web
    name: prisma-desk
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PRISMA_SITE_URL
        value: https://www.prismasuecia.se
      - key: ENABLE_MAIL
        value: "false"
      - key: ENABLE_OPENAI
        value: "false"
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PRISMA_DESK_PASSWORD
        sync: false
      - key: PRISMA_DESK_SECRET_KEY
        generateValue: true
